Repository tidyverse/dplyr, pull requests merged in 2018-12, with the labels that each got.

#4022 Performance of bind rows(.id =)
  inst/include/tools/SymbolVector.h
  inst/include/tools/utils.h
  src/bind.cpp
  src/utils.cpp
Labels: performance :rocket:

#3998 + group_walk()
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/compat-purrr.R
  R/funs.R
  R/group_map.R
  R/group_nest.R
  R/group_split.R
  man/funs.Rd
  man/group_by.Rd
  man/group_by_all.Rd
  man/group_data.Rd
  man/group_indices.Rd
  man/group_map.Rd
  man/group_nest.Rd
  man/group_size.Rd
  man/group_split.Rd
  man/groups.Rd
  tests/testthat/test-group_map.R
Labels: feature

#3978 make rlang lambdas inherit from the data mask.
  inst/include/dplyr/data/DataMask.h
  tests/testthat/test-mutate.r
Labels: feature

#4008 Experiment with .preserve = FALSE as default
  NEWS.md
  R/RcppExports.R
  R/colwise-filter.R
  R/dataframe.R
  R/manip.r
  R/tbl-df.r
  R/zzz.r
  man/filter.Rd
  man/filter_all.Rd
  man/se-deprecated.Rd
  man/slice.Rd
  src/RcppExports.cpp
  src/group_indices.cpp
  tests/testthat/test-empty-groups.R
  tests/testthat/test-filter.r
  tests/testthat/test-slice.r
Labels: feature

#4031 group_trim() to drop unused levels of grouping factors
  NAMESPACE
  NEWS.md
  R/group_trim.R
  man/group_by.Rd
  man/group_by_all.Rd
  man/group_data.Rd
  man/group_indices.Rd
  man/group_map.Rd
  man/group_nest.Rd
  man/group_size.Rd
  man/group_split.Rd
  man/group_trim.Rd
  man/groups.Rd
  tests/testthat/test-group_trim.R
Labels: data frame, feature

#3991 User defined column name in tally/count
  R/count-tally.R
  man/tally.Rd
  tests/testthat/test-count-tally.r
Labels: feature
