Repository tidyverse/dplyr, pull requests merged in 2019-12, with the labels that each got.

#4642 faster internal group_keys()
  R/group_keys.R
  inst/bench/bench.R
  src/dplyr.cpp
  src/dplyr/symbols.h
Labels: performance :rocket:

#4102 pull() can also return named vectors
  R/pull.R
  man/pull.Rd
  tests/testthat/test-pull.R
Labels: breaking change :skull_and_crossbones:

#4480 Improve Starwars data set gender and sex classifications of characters
  NEWS.md
  R/data-starwars.R
  data-raw/starwars.R
  data-raw/starwars.csv
  data/starwars.rda
  man/starwars.Rd
Labels: tidy-dev-day :nerd_face:
